Tao/Tao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsCore.urls')),
]

Tao/newsCore/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('about/', views.aboutPage, name='aboutPage'),
    path('news/post/<int:pk>/', views.postDetail, name='postDetail'),
    path('news/delete-post/<int:pk>/', views.deletePost, name='deletePost'),
    path('news/edit-post/<int:pk>/', views.editPost, name='editPost'),
    path('news/all/', views.allNews, name='allNews'),
    path('news/add/', views.addPost, name='addPost'),
]

Tao/newsCore/models.py
from django.db import models
from datetime import datetime


# Create your models here.
class Post(models.Model):
    title = models.CharField("Title", max_length=255)
    postDate = models.DateTimeField("Post published date and time", default=datetime.today())
    image = models.CharField("Image", max_length=500, null=True, blank=True)
    content = models.TextField("Content")

    def __str__(self):
        return f"{self.title} - {self.postDate}"

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

Tao/newsCore/forms.py
from django import forms
from . models import Post

class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'image', 'content')

Tao/newsCore/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import AddPostForm


# Create your views here.
def homePage(request):
    posts = Post.objects.all().order_by('-postDate')[:3]
    return render(request, "site/index.html", {
        'posts': posts
    })


def aboutPage(request):
    title = 'Tao'
    return render(request, "site/about.html", {
        "title": title
    })


def postDetail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, "user/post-detail.html", {
        'post': post
    })

def allNews(request):
    posts = Post.objects.all().order_by('-postDate')
    return render(request, "site/all-news.html", {
        'posts': posts
    })

def addPost(request):
    if request.method == "POST":
        form = AddPostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("homePage")
    else:
        form = AddPostForm()

    return render(request, "user/add-post.html", {
        'form': form
    })

def deletePost(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        post.delete()
        return redirect("allNews")
    return render(request, "user/delete-post.html", {
        'post': post
    })

def editPost(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = AddPostForm(request.POST or None, instance=post)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("postDetail", pk=post.pk)
    else:
        form = AddPostForm()
    return render(request, "user/edit-post.html", {
        'post': post,
        'form': form
    })

Tao/newsCore/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <link rel="shortcut icon" href="{% static './img/SiteIcon.webp' %}" type="image/x-icon">
</head>
<body>
<header class="header" id="header" style="padding-bottom: 15px;">
    <div class="container">
        <a id="burger-menu-button" class="burger-menu-button" onclick="burgerMenuAction()"><img
                src="{% static './img/butterfly_menu_icon.webp' %}" width="45px" height="45px"></a>
        <div class="menu-list">
            <img src="{% static './img/butterfly_menu_icon.webp' %}" width="60px">
            <a href="{% url 'homePage' %}">Main</a>
            <a href="{% url 'aboutPage' %}">About</a>
            <a href="{% url 'allNews' %}" class="allNewsBtn">All News</a>
            <a href="{% url 'addPost' %}">Add Post</a>
            <a href="https://candybox2.github.io/candybox/" target="_blank">For Fun</a>
        </div>
        <div class="menu-list-right">
            <a id="SignUpBtn">Sign Up</a>
            <a id="LogInBtn">Log In</a>
        </div>
        <div class="mobile-menu-list" id="mobile-menu-list" style="display: none;">
            <a href="{% url 'homePage' %}">Main</a>
            <a href="{% url 'aboutPage' %}">About</a>
            <a href="https://candybox2.github.io/candybox/" target="_blank">For Fun</a>
        </div>
    </div>
</header>

{% block content %}
{% endblock %}

<footer class="footer">
    <div class="container">
        <p>&copy;Wangsheng Funeral Parlor</p>
    </div>
</footer>
<form>
    <div id="Modal" class="modal">
    <div class="modal-content">
        <div class="modal-header">
            <span class="close">&times;</span>
            <p class="modal-sign-up" onclick="SignUpFun()">Sign Up</p>
            <p class="modal-log-in" onclick="SignUpFun()">Log In</p>
        </div>
        <div class="modal-body">
            <div class="signup-content" id="signup-content" style="display: block;">
                <label for="mname">First name</label><br>
                <input type="text" name="SignUpName" placeholder="Enter the name"><br>
                <label for="memail">Email</label><br>
                <input type="email" name="SignUpEmail" placeholder="Enter the email"><br>
                <label for="mpassword">Password</label><br>
                <input type="password" name="SignUpPassword" placeholder="Enter the password"><br>
            </div>
            <div class="login-content" id="login-content" style="display: none;">
                <label for="mname">First name/Email</label><br>
                <input type="text" name="LogInName" placeholder="Enter the name/email"><br>
                <label for="mpassword">Password</label><br>
                <input type="password" name="LogInPassword" placeholder="Enter the password"><br>
            </div>
            <button type="submit">Sign Up</button>
        </div>
    </div>
    </div>
</form>

<script src="{% static './js/script.js' %}"></script>
</body>
</html>

Tao/newsCore/templates/index.html
{% extends 'base.html' %}

{% block title %}
Hu
{% endblock %}

{% block content %}

<div class="content">
    <div class="main">
        <div class="container">
            <h1>Tao</h1>
            <p>The 77th Director of the Wangsheng Funeral Parlor. She took over the business at a rather young age.</p>
            <a href="#" class="main-button">Read</a>
        </div>
    </div>
    <div class="news">
        <div class="container">
            <h2>News</h2>
            {% for post in posts %}
            <div class="card">
                <h3 class="card-title">{{ post.title }}</h3>
                <h4 class="card-date">{{ post.postDate }}</h4>
                <p class="card-content">{{ post.content|truncatewords:15 }}</p>
                <a href="{% url 'postDetail' pk=post.pk %}" class="main-button">More</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

Tao/newsCore/templates/post-detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}

<div class="content">
    <div class="post-detail-main">
        <div class="container">
            <h1>{{ post.title }}</h1>
            <p>{{ post.content }}</p>
        </div>
    </div>
</div>

{% endblock %}

Tao/newsCore/templates/site/about.html
{% extends '../base.html' %}

{% block title %}
Hu Tao
{% endblock %}

{% block content %}

<div class="content">
    <div class="main">
        <div class="container">
            <h1>Genshin News and Hu Tao!)</h1>
            <p>all about hu tao and some news</p>
        </div>
    </div>
</div>

{% endblock %}

Tao/newsCore/templates/site/all-news.html
{% extends 'base.html' %}

{% block title %}
All News
{% endblock %}

{% block content %}

<div class="content">
    <div class="news">
        <div class="container">
            <h2>All News</h2>
            {% for post in posts %}
            <div class="card">
                <h3 class="card-title">{{ post.title }}</h3>
                <h4 class="card-date">{{ post.postDate }}</h4>
                <p class="card-content">{{ post.content|truncatewords:20 }}</p>
                <a href="{% url 'postDetail' pk=post.pk %}" class="main-button">More</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

Tao/newsCore/templates/site/index.html
{% extends '../base.html' %}

{% block title %}
Hu
{% endblock %}

{% block content %}

<div class="content">
    <div class="main">
        <div class="container">
            <h1>Tao</h1>
            <p>Info bout Hu Tao on HoyoWiki</p>
            <a href="https://wiki.hoyolab.com/pc/genshin/entry/34" target="_blank" class="main-button">Watch</a>
        </div>
    </div>
    <div class="news">
        <div class="container">
            <h2>Last News</h2>
            {% for post in posts %}
            <div class="card">
                <h3 class="card-title">{{ post.title }}</h3>
                <h4 class="card-date">{{ post.postDate }}</h4>
                <a href="{% url 'postDetail' pk=post.pk %}" class="main-button">More</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

Tao/newsCore/templates/user/add-post.html
{% extends 'base.html' %}

{% block title %}
Add Post
{% endblock %}

{% block content %}
<style>
h2 {
font-size: 40px;
padding-bottom: 20px;
}
#id_title, #id_image, #id_content {
padding: 10px;
border-radius: 10px;
border: 1px solid black;
display: block;
width: 100%;
margin-top: 5px;
margin-bottom: 15px;
font-size: 20px;
}
button {
display: inline-block;
background-color: brown;
border: 2px solid brown;
padding: 10px 40px;
text-decoration: none;
color: white;
border-radius: 15px;
transition: 0.3s ease-in-out;
font-size: 20px;
margin-top: 10px;
}
button:hover {
background-color: white;
color: brown;
}
label {
font-size: 25px;
}
</style>

<div class="content">
    <div class="container">
        <h2>Add Post</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button>Add</button>
        </form>
    </div>
</div>


{% endblock %}

Tao/newsCore/templates/user/delete-post.html
{% extends '../base.html' %}

{% block title %}
Delete Post
{% endblock %}

{% block content %}
<style>
    button, #deletepostno{
    display: inline-block;
    background-color: brown;
    border: 2px solid brown;
    padding: 10px 40px;
    text-decoration: none;
    color: white;
    border-radius: 15px;
    transition: 0.3s ease-in-out;
    font-size: 20px;
    margin-top: 20px;
    margin-right: 20px;
    width: 120px;
    text-align: center;
    }
    button:hover, #deletepostno:hover{
    background-color: white;
    color: brown;
    }
</style>
<div class="content">
    <div class="container">
    <h1>Delete Post {{ post.title }}?</h1>
    <form method="POST">
        {% csrf_token %}
        <button>Yes</button>
        <a id="deletepostno" href="{% url 'postDetail' pk=post.pk %}">No</a>
    </form>
    </div>
</div>

{% endblock %}

Tao/newsCore/templates/user/edit-post.html
{% extends 'base.html' %}

{% block title %}
Edit Post
{% endblock %}

{% block content %}
<style>
h2 {
font-size: 40px;
padding-bottom: 20px;
}
#id_title, #id_image, #id_content {
padding: 10px;
border-radius: 10px;
border: 1px solid black;
display: block;
width: 100%;
margin-top: 5px;
margin-bottom: 15px;
font-size: 20px;
}
button {
display: inline-block;
background-color: brown;
border: 2px solid brown;
padding: 10px 40px;
text-decoration: none;
color: white;
border-radius: 15px;
transition: 0.3s ease-in-out;
font-size: 20px;
margin-top: 10px;
}
button:hover {
background-color: white;
color: brown;
}
label {
font-size: 25px;
}
</style>
<div class="content">
    <div class="container">
        <h2>Edit Post</h2>
        <form method="POST">
            {% csrf_token %}
            <label for="id_title">Title:</label>
            <input value="{{ post.title }}" type="text" name="title" maxlength="255" required="" id="id_title">
            {% if post.image %}
            <label for="id_image">Image:</label>
            <input value="{{ post.image }}" type="text" name="image" maxlength="500" id="id_image">
            {% else %}
            <label for="id_image">Image:</label>
            <input value="" type="text" name="image" maxlength="500" id="id_image">
            {% endif %}
            <label for="id_content">Content:</label>
            <textarea name="content" cols="40" rows="10" required="" id="id_content">
                {{ post.content }}
            </textarea>

            <button>Edit</button>
        </form>
    </div>
</div>

{% endblock %}

Tao/newsCore/templates/user/post-detail.html
{% extends '../base.html' %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}

<div class="content">
    <div class="pd-main">
        <div class="container">
            <a href="{% url 'homePage' %}">Back</a>
            <h1>{{ post.title }}</h1>
            {% if post.image %}
            <div style="width: 100%;">
                <img src="{{ post.image }}" alt="{{ post.title }}">
            </div>
            {% else %}
            <span></span>
            {% endif %}
            <p>{{ post.content }}</p>
            <p class="postdate">{{ post.postDate }}</p>
            <a href="{% url 'editPost' pk=post.pk %}" class="postedit">Edit</a>
            <a href="{% url 'deletePost' pk=post.pk %}" class="postedit">Delete</a>
        </div>
    </div>
</div>

{% endblock %}